AtlantidaBankAPI/AtlantidaBankCliente/Controllers/CreditCardController.cs
using AtlantidaBankCliente.Models;
using AtlantidaBankCliente.Models.ViewModels;
using AtlantidaBankCliente.Services;
using Microsoft.AspNetCore.Mvc;

namespace AtlantidaBankCliente.Controllers
{
    public class CreditCardController : Controller
    {
        private readonly SessionService _sessionService;
        private readonly CreditCardService _creditCardService;
        private readonly ILogger<CreditCardController> _logger;

        public CreditCardController(SessionService sessionService, CreditCardService creditCardService, ILogger<CreditCardController> logger)
        {
            this._sessionService = sessionService;
            this._creditCardService = creditCardService;
            this._logger = logger;
        }

        [HttpGet]
        public async Task<IActionResult> AccountStatus()
        {
            try
            {
                //Obteniendo datos de la cuenta
                var session = _sessionService.GetSession();
                AccountStatementDetailModel model = new AccountStatementDetailModel()
                {
                    UserId = session.UserId.ToString(),
                    CrediCardId = session.CrediCardId.ToString()
                };

                CreditCardModel creditCardModel = new CreditCardModel()
                {
                    CrediCardId = session.CrediCardId.ToString()
                };

                _logger.LogInformation("Obteniendo datos de la tarjeta de credito");

                var AccountStatementDetail = await _creditCardService.GetAccountStatementDetail(model);
                ViewBag.AccountStatementDetail = AccountStatementDetail;

                var TotalPurchases = await _creditCardService.GetTotalPurchases(creditCardModel);
                ViewBag.TotalPurchases = TotalPurchases;

                var BonifiableInterest = await _creditCardService.GetBonifiableInterest(creditCardModel);
                ViewBag.BonifiableInterest = BonifiableInterest.BonifiableInterest;

                var MinimumPayment = await _creditCardService.GetCalculateMinimumPayment(creditCardModel);
                ViewBag.MinimumPayment = MinimumPayment.MinimumPayment;

                var TotalAmountToPay = await _creditCardService.GetTotalAmountToPay(creditCardModel);
                ViewBag.TotalAmountToPay = TotalAmountToPay.TotalAmountToPay;

                var TotalAmountToPayWithInterest = await _creditCardService.GetTotalAmountToPayWithInterest(creditCardModel);
                ViewBag.TotalAmountToPayWithInterest = TotalAmountToPayWithInterest.TotalCashAmountToPayWithInterest;

                var ListCurrentMonthPurchases = await _creditCardService.GetCurrentMonthPurchases(creditCardModel);
                ViewBag.ListCurrentMonthPurchases = ListCurrentMonthPurchases;

                return View();
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error","Home", new { errorMessage = "Hubo un error al procesar la solicitud. Error: " + ex.Message + " Detalle Error: " + ex.InnerException } );
            }
        }

        [HttpGet]
        public async Task<IActionResult> Transactions()
        {
            try
            {
                //Obteniendo datos de la cuenta
                var session = _sessionService.GetSession();

                CreditCardModel creditCardModel = new CreditCardModel()
                {
                    CrediCardId = session.CrediCardId.ToString()
                };

                var AllTransactions = await _creditCardService.GetAllTransactionsForCreditCard(creditCardModel);
                ViewBag.AllTransactions = AllTransactions;

                return View();
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error", "Home", new { errorMessage = "Hubo un error al procesar la solicitud. Error: " + ex.Message + " Detalle Error: " + ex.InnerException });
            }
            
        }
    }
}

AtlantidaBankAPI/AtlantidaBankCliente/Controllers/ShoppingController.cs
using AtlantidaBankCliente.Models;
using AtlantidaBankCliente.Models.ViewModels;
using AtlantidaBankCliente.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;

namespace AtlantidaBankCliente.Controllers
{
    public class ShoppingController : Controller
    {
        private readonly SessionService _sessionService;
        private readonly ShoppingService _shoppingService;

        public ShoppingController(SessionService sessionService, ShoppingService shoppingService)
        {
            this._sessionService = sessionService;
            this._shoppingService = shoppingService;
        }

        [HttpGet]
        public IActionResult AddPurchase()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddPurchase(TransactionViewModel model)
        {
            if (!ModelState.IsValid)
            {
                AddErrorsFromModel(ModelState.Values);
                return View();
            }

            try
            {
                var session = _sessionService.GetSession();

                model.IPAddress = session.IPAddress;
                model.CrediCardId = session.CrediCardId.ToString();

                var mMessage = await _shoppingService.AddPurchase(model);

                TempData["Message"] = mMessage;

                return View();
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error", "Home", new { errorMessage = "Hubo un error al procesar la solicitud. Error: " + ex.Message + " Detalle Error: " + ex.InnerException });
            }
  
        }


        [HttpGet]
        public IActionResult MakePayment()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> MakePayment(TransactionPayViewModel model)
        {

            if (!ModelState.IsValid)
            {
                AddErrorsFromModel(ModelState.Values);
                return View();
            }

            try
            {
                var session = _sessionService.GetSession();

                model.IPAddress = session.IPAddress;
                model.CrediCardId = session.CrediCardId.ToString();
                model.Description = "Realización de pago";


                var mMessage = await _shoppingService.MakePayment(model);

                TempData["Message"] = mMessage;

                return View();
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error", "Home", new { errorMessage = "Hubo un error al procesar la solicitud. Error: " + ex.Message + " Detalle Error: " + ex.InnerException });
            }
            
        }


        private void AddErrorsFromModel(ModelStateDictionary.ValueEnumerable values)
        {
            foreach (ModelStateEntry modelState in values)
                foreach (ModelError error in modelState.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.ErrorMessage.ToString());

                }
        }

    }
}

AtlantidaBankAPI/AtlantidaBankCliente/Views/Shared/_Layout _Authenticated.cshtml
@inject IHttpContextAccessor _session;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AtlantidaBankCliente</title>
    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/plugins/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Tempusdominus Bootstrap 4 -->
    <link rel="stylesheet" href="~/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
    <!-- iCheck -->
    <link rel="stylesheet" href="~/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- JQVMap -->
    <link rel="stylesheet" href="~/plugins/jqvmap/jqvmap.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/dist/css/adminlte.min.css">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="~/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="~/plugins/daterangepicker/daterangepicker.css">
    <!-- summernote -->
    <link rel="stylesheet" href="~/plugins/summernote/summernote-bs4.min.css">

    @RenderSection("Styles", required: false)
</head>
<body class="hold-transition sidebar-mini">
    <!-- Site wrapper -->
    <div class="wrapper">

        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <!-- Left navbar links -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
                </li>
                <li class="nav-item d-none d-sm-inline-block">
                    <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Main">Home</a>
                </li>
            </ul>


        </nav>
        <!-- /.navbar -->
        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <!-- Brand Logo -->
            <a asp-area="" asp-controller="Home" asp-action="Main" class="brand-link">
                <img src="~/dist/img/logo.png" alt="Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
                <span class="brand-text font-weight-light">Banco Atlántida</span>
            </a>

            <!-- Sidebar -->
            <div class="sidebar">
                <!-- Sidebar user (optional) -->
                <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                    <div class="info text-white">
                        <h5>@_session.HttpContext.Session.GetString("FirstName")</h5>
                        <h6>@_session.HttpContext.Session.GetString("Email")</h6>
                        <hr />
                        <a asp-area="" asp-controller="Home" asp-action="Logout">
                            <i class="fas fa-power-off"></i>
                            <small class="text-white"> Cerrar sesión</small>
                        </a>
                    </div>
                </div>

                
                <!-- Sidebar Menu -->
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">

                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="CreditCard" asp-action="AccountStatus">
                                <i class="nav-icon fas fa-piggy-bank"></i>
                                
                                <p>
                                    Estado de cuenta
                                </p>
                            </a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Shopping" asp-action="AddPurchase">
                                <i class="nav-icon fas fa-store"></i>
                                <p>
                                    Compras
                                </p>
                            </a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Shopping" asp-action="MakePayment">
                                <i class="nav-icon fas fa-hand-holding-usd"></i>
                                <p>
                                    Pagos
                                </p>
                            </a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="CreditCard" asp-action="Transactions">
                                <i class="nav-icon fas fa-landmark"></i>
                                <p>
                                    Transacciones
                                </p>
                            </a>
                        </li>

                    </ul>
                </nav>
                <!-- /.sidebar-menu -->
            </div>
            <!-- /.sidebar -->
        </aside>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <main role="main" class="content">
                <div class="container-fluid">
                    @RenderBody()
                </div>
            </main>
        </div>

        <footer class="main-footer">
            <strong>Copyright &copy; @DateTime.Now.Year <a href="https://www.bancoatlantida.com.sv/">Banco Atlántida</a>.</strong> All rights reserved.
        </footer>

        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
        </aside>
        <!-- /.control-sidebar -->
    </div>
    <!-- ./wrapper -->
    </div>


    <script src="~/plugins/jquery/jquery.min.js"></script>
    <!-- jQuery UI 1.11.4 -->
    <script src="~/plugins/jquery-ui/jquery-ui.min.js"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
        $.widget.bridge('uibutton', $.ui.button)
    </script>
    <!-- Bootstrap 4 -->
    <script src="~/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- ChartJS -->
    <script src="~/plugins/chart.js/Chart.min.js"></script>
    <!-- Sparkline -->
    <script src="~/plugins/sparklines/sparkline.js"></script>
    <!-- JQVMap -->
    <script src="~/plugins/jqvmap/jquery.vmap.min.js"></script>
    <script src="~/plugins/jqvmap/maps/jquery.vmap.usa.js"></script>
    <!-- jQuery Knob Chart -->
    <script src="~/plugins/jquery-knob/jquery.knob.min.js"></script>
    <!-- daterangepicker -->
    <script src="~/plugins/moment/moment.min.js"></script>
    <script src="~/plugins/daterangepicker/daterangepicker.js"></script>
    <!-- Tempusdominus Bootstrap 4 -->
    <script src="~/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
    <!-- Summernote -->
    <script src="~/plugins/summernote/summernote-bs4.min.js"></script>
    <!-- overlayScrollbars -->
    <script src="~/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/dist/js/adminlte.js"></script>


    @RenderSection("Scripts", required: false)
</body>
</html>

AtlantidaBankAPI/AtlantidaBankCliente/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AtlantidaBankCliente</title>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="plugins/fontawesome-free/css/all.min.css">
    <!-- icheck bootstrap -->
    <link rel="stylesheet" href="plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="dist/css/adminlte.min.css">
    @RenderSection("Styles", required: false)
</head>
<body class="hold-transition login-page">

    <div class="login-box">

        @RenderBody()

    </div>

    <!-- jQuery -->
    <script src="plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="dist/js/adminlte.min.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>